### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by csenol** [odkr/pandoc-zotxt.lua#3]
Hello. I am quite new to zotero and pandoc.
When I am using zotero with emacs, zotero links are inserted like ```(zotero://select/items/1_LFZY74D5)```

I was hoping with this filter, pandoc exports would replace such zotero links with a URL in case the referenced item in Zotero is a web page. However, it is not the case.

Am I interpreting this project wrong or do I lack some configuration?

**Comment by odkr** [comment]
Hey there. I'm not quite sure what you mean by "Zotero links." I'm on the vi side of the editor wars and have never seriously used Emacs. Could you say a bit more about what it is that you want to do, your setup, and your workflow?

**Comment by csenol** [comment]
Nevermind, I think I found the issue. I was using pandoc with output format markdown but in standard markdown pandoc does not produce citations, with gfm or HTML this project works as expected. Thanks a lot

**Comment by odkr** [comment]
That's odd. Pandoc does process citations regardless of the output format you choose. So, I'm still confused about what went wrong. At any rate, great that you got things to work! :-)
